// <auto-generated />
using System;
using System.Collections.Generic;
using AB.SmokPrzewodnik.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AB.SmokPrzewodnik.Infrastructure.Migrations
{
    [DbContext(typeof(Database.DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Navigation.NavigationEvent", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("HazardCode")
                        .HasColumnType("text")
                        .HasColumnName("hazard_code");

                    b.Property<string>("LandmarkCode")
                        .HasColumnType("text")
                        .HasColumnName("landmark_code");

                    b.Property<string>("LocalizedParameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("localized_parameters");

                    b.Property<string>("Maneuver")
                        .HasColumnType("jsonb")
                        .HasColumnName("maneuver");

                    b.Property<decimal?>("RemainingDistanceMetres")
                        .HasColumnType("numeric")
                        .HasColumnName("remaining_distance_metres");

                    b.Property<string>("SupportedFeedbackPatterns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("supported_feedback_patterns");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("urgency");

                    b.HasKey("SessionId", "Sequence");

                    b.ToTable("navigation_events", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Navigation.NavigationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("ActiveRoute")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_route");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EffectiveRouteRequest")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("effective_route_request");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("hash");

                    b.Property<string>("LatestProgress")
                        .HasColumnType("jsonb")
                        .HasColumnName("latest_progress");

                    b.Property<long>("NextEventSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_event_sequence");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("navigation_sessions", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.FeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudienceTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audience_tags");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<string>("LocalizedContent")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("localized_content");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provenance");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("CityId", "PublishedAt");

                    b.ToTable("feed_items", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.FeedItemEntityLink", b =>
                {
                    b.Property<Guid>("FeedItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_item_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.HasKey("FeedItemId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("feed_item_entities", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.Itinerary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("LocalizedTitle")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("localized_title");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("_routeLegReferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("route_leg_references");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "StartsAt");

                    b.ToTable("itineraries", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.ItineraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("PlannedArrival")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_arrival");

                    b.Property<DateTimeOffset?>("PlannedDeparture")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_departure");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("itinerary_id")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("itinerary_id", "Position")
                        .IsUnique();

                    b.ToTable("itinerary_items", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.SuggestionProjection", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("SuggestedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_entity_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reason_codes");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("score");

                    b.HasKey("AccountId", "SuggestedEntityId");

                    b.HasIndex("SuggestedEntityId");

                    b.HasIndex("AccountId", "Score");

                    b.ToTable("suggestion_projections", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Profiles.AccountAccessibilityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("JourneyHistorySyncEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("journey_history_sync_enabled");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("server_version");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("accessibility_profiles", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Routing.RoutePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Alternatives")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("alternatives");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("route_plans", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.AccessibilityFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attribute_code");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<string>("CodeValue")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_value");

                    b.Property<decimal>("ConfidenceWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_weight");

                    b.Property<string>("EvidenceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("evidence_kind");

                    b.Property<string>("GraphElementType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("graph_element_type");

                    b.Property<string>("GraphExternalElementId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("graph_external_element_id");

                    b.Property<string>("GraphRoutingProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("graph_routing_provider");

                    b.Property<string>("GraphVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("graph_version");

                    b.Property<string>("NumberUnitCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number_unit_code");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("numeric")
                        .HasColumnName("number_value");

                    b.Property<Guid?>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid?>("SourceAssertionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_assertion_id");

                    b.Property<Guid?>("SpatialEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("spatial_entity_id");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_kind");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value_kind");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssertionId");

                    b.HasIndex("SpatialEntityId", "AttributeCode");

                    b.ToTable("accessibility_facts", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("default_locale");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultConfidenceWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("default_confidence_weight");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("license");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_code");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("ProviderCode")
                        .IsUnique();

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.EventCategory", b =>
                {
                    b.Property<Guid>("SpatialEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("spatial_entity_id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_code");

                    b.HasKey("SpatialEntityId", "Code");

                    b.ToTable("event_categories", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.SpatialEntityDetails", b =>
                {
                    b.Property<Guid>("SpatialEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("spatial_entity_id");

                    b.Property<string>("detail_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("SpatialEntityId");

                    b.ToTable("spatial_entity_details", (string)null);

                    b.HasDiscriminator<string>("detail_type").HasValue("SpatialEntityDetails");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.EntitySourceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("license");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("TransformVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transform_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("entity_source_links", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.EntityTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Locale")
                        .IsUnique();

                    b.ToTable("entity_translations", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.SourceAssertion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssertionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("assertion_type");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("TransformVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transform_version");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("source_assertions", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Confidence", "AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity.Confidence#ConfidenceAssessment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("EvaluatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("confidence_evaluated_at");

                            b1.Property<int>("EvidenceCount")
                                .HasColumnType("integer")
                                .HasColumnName("confidence_evidence_count");

                            b1.Property<decimal>("Score")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("confidence_score");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("confidence_state");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("CityId", "Kind");

                    b.HasIndex("UpdatedAt", "Id");

                    b.ToTable("spatial_entities", (string)null);
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.EventDetails", b =>
                {
                    b.HasBaseType("AB.SmokPrzewodnik.Domain.Spatial.Details.SpatialEntityDetails");

                    b.Property<string>("BookingUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("event_booking_uri");

                    b.Property<long?>("Capacity")
                        .HasColumnType("bigint")
                        .HasColumnName("event_capacity");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_ends_at");

                    b.Property<Guid?>("OrganizerEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_organizer_entity_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_starts_at");

                    b.HasIndex("OrganizerEntityId");

                    b.HasIndex("StartsAt", "EndsAt");

                    b.HasDiscriminator().HasValue("event");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.InfrastructureDetails", b =>
                {
                    b.HasBaseType("AB.SmokPrzewodnik.Domain.Spatial.Details.SpatialEntityDetails");

                    b.Property<string>("InfrastructureCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("infrastructure_code");

                    b.Property<string>("MaintenanceReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("infrastructure_maintenance_reference");

                    b.Property<string>("OperationalState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("infrastructure_operational_state");

                    b.HasDiscriminator().HasValue("infrastructure");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.ObstacleDetails", b =>
                {
                    b.HasBaseType("AB.SmokPrzewodnik.Domain.Spatial.Details.SpatialEntityDetails");

                    b.Property<string>("AffectedTravelModes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("obstacle_affected_travel_modes");

                    b.Property<DateTimeOffset?>("ExpectedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("obstacle_expected_until");

                    b.Property<string>("ObstacleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("obstacle_code");

                    b.Property<long>("Severity")
                        .HasColumnType("bigint")
                        .HasColumnName("obstacle_severity");

                    b.HasDiscriminator().HasValue("obstacle");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.PlaceDetails", b =>
                {
                    b.HasBaseType("AB.SmokPrzewodnik.Domain.Spatial.Details.SpatialEntityDetails");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("place_category_code");

                    b.Property<string>("Contact")
                        .HasColumnType("jsonb")
                        .HasColumnName("place_contact");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("place_opening_hours");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("place_website");

                    b.HasDiscriminator().HasValue("place");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Navigation.NavigationEvent", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Navigation.NavigationSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.FeedItem", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.City", "City")
                        .WithMany("FeedItems")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.DataSource", "Source")
                        .WithMany("FeedItems")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.FeedItemEntityLink", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", "Entity")
                        .WithMany("FeedItemLinks")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AB.SmokPrzewodnik.Domain.Planning.FeedItem", "FeedItem")
                        .WithMany("EntityLinks")
                        .HasForeignKey("FeedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("FeedItem");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.ItineraryItem", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", "Entity")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AB.SmokPrzewodnik.Domain.Planning.Itinerary", null)
                        .WithMany("Items")
                        .HasForeignKey("itinerary_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.SuggestionProjection", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", "SuggestedEntity")
                        .WithMany("Suggestions")
                        .HasForeignKey("SuggestedEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuggestedEntity");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.AccessibilityFact", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SourceAssertion", "SourceAssertion")
                        .WithMany("AccessibilityFacts")
                        .HasForeignKey("SourceAssertionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", "SpatialEntity")
                        .WithMany("AccessibilityFacts")
                        .HasForeignKey("SpatialEntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SourceAssertion");

                    b.Navigation("SpatialEntity");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.EventCategory", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.Details.EventDetails", null)
                        .WithMany("Categories")
                        .HasForeignKey("SpatialEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.SpatialEntityDetails", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", null)
                        .WithOne("Details")
                        .HasForeignKey("AB.SmokPrzewodnik.Domain.Spatial.Details.SpatialEntityDetails", "SpatialEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.EntitySourceLink", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", "Entity")
                        .WithMany("SourceLinks")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.DataSource", "Source")
                        .WithMany("SourceLinks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.EntityTranslation", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", "Entity")
                        .WithMany("Translations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.SourceAssertion", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.DataSource", "Source")
                        .WithMany("SourceAssertions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.City", "City")
                        .WithMany("SpatialEntities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.EventDetails", b =>
                {
                    b.HasOne("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.FeedItem", b =>
                {
                    b.Navigation("EntityLinks");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Planning.Itinerary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.City", b =>
                {
                    b.Navigation("FeedItems");

                    b.Navigation("SpatialEntities");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.DataSource", b =>
                {
                    b.Navigation("FeedItems");

                    b.Navigation("SourceAssertions");

                    b.Navigation("SourceLinks");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.SourceAssertion", b =>
                {
                    b.Navigation("AccessibilityFacts");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.SpatialEntity", b =>
                {
                    b.Navigation("AccessibilityFacts");

                    b.Navigation("Details");

                    b.Navigation("FeedItemLinks");

                    b.Navigation("ItineraryItems");

                    b.Navigation("SourceLinks");

                    b.Navigation("Suggestions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AB.SmokPrzewodnik.Domain.Spatial.Details.EventDetails", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
