<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AB.SmokPrzewodnik.Application/AB.SmokPrzewodnik.Application.csproj" />
    <ProjectReference Include="../AB.SmokPrzewodnik.Domain/AB.SmokPrzewodnik.Domain.csproj" />
  </ItemGroup>
</Project>
